[build]
command = """
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y &&
    source $HOME/.cargo/env &&
    rustup default stable &&
    curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
  """

[build.environment]
NODE_VERSION = "22"
