[build]
command = "curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh && npm run build"
publish = "dist"

[build.environment]
NODE_VERSION = "22"
RUST_VERSION = "1.84.1"

[[headers]]
# Define headers for WASM files
for = "/*.wasm"
[headers.values]
Content-Type = "application/wasm"
Cache-Control = "public, max-age=31536000"
